import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { GetStaticProps } from "next";

import styles from "../styles/Home.module.css";
import { getSortedTasksData } from "../lib/tasks";

export default function Home({
  allTasksData,
}: {
  allTasksData: {
    id: string;
    title: string;
    description: string;
    tags: string[];
  }[];
}) {
  // Note that we are only extracting select fields from the spec data since
  // users are most likely going to search for metadata rather than the command contents.

  const [query, setQuery] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          type="text"
        />
        <ul>
          {allTasksData
            .filter(
              ({ title, description, tags }) =>
                title.toLowerCase().includes(query.toLowerCase()) ||
                description.toLowerCase().includes(query.toLowerCase()) ||
                tags.find((tag) =>
                  tag.toLowerCase().includes(query.toLowerCase())
                )
            )
            .map(({ id, title, description, tags }) => (
              <li key={id}>
                <h2>
                  <Link href={`/tasks/${id}`}>
                    <a>{title}</a>
                  </Link>
                </h2>
                <p>{description}</p>
                <br />
                {tags.join(", ")}
              </li>
            ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allTasksData = getSortedTasksData();
  return {
    props: {
      allTasksData,
    },
  };
};
